名称: 自动评分

开启:
  日程安排:
    - cron: '0 17 * * *'  # UTC 17:00 (北京时间1:00)
  工作流触发:

职位:
  分数:
    运行于: ubuntu-最新
    
    步骤:
    - 使用: actions/checkout@v2
    
    - name: 安装Python
      使用：actions/setup-python@v2
      与：
        python-version: '3.x'
    
    - name: 安装依赖项
      运行: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - 名称: 运行脚本
      环境:
        音乐_U: ${{ secrets.MUSIC_U }}
        跨站请求伪造: ${{ secrets.CSRF }}
        NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
        电子邮件密码: ${{ secrets.EMAIL_PASSWORD }}
        SMTP服务器: ${{ secrets.SMTP_SERVER }}
        SMTP端口: ${{ secrets.SMTP_PORT }}
等待时间（分钟）: ${{ secrets.WAIT_TIME_MIN }}
        等待时间最大值: ${{ secrets.WAIT_TIME_MAX }}
        分数: ${{ secrets.SCORE }}
      运行: python main.py
